---
abstract: 'Data Validator to check for well formed UUIDs'
author:
  - 'Robert Stone <drzigman@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Readonly: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Validate-UUID
requires:
  Exporter: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/drzigman/data-validate-uuid/issues
  homepage: http://search.cpan.org/dist/Data-Validate-UUID
  repository: git://github.com/drzigman/data-validate-uuid.git
version: 0.1.0
